### ISSUE TITLE
Test for songs index doesn't raise error if the page 404s.

### ISSUE THREAD

**Issue by spencer1248** [learn-co-curriculum/playlister-sinatra#1]
Currently it just complains that it doesn't find content, would be nice if it broke on the 404.

**Comment by deniznida** [comment]
We're using feature specs here, so to test a 404, I'd normally use a controller spec, but in a feature spec, hows this:

```ruby
it 'responds with a 200 status code' do
  visit '/songs'
  expect(page.status_code).to eq(200)
end

it 'does not respond with a 404'
  visit '/songs'
  expect(page.status_code).to_not eq(404)
end
```

**Comment by spencer1248** [comment]
Hm, my comment was from over a year ago so I don't really remember anything, but that seems fine. I think you just need one or the other, so that if it 404s you can see "expected 200, got 404".
