### ISSUE TITLE
Error in 04_basic_view_spec.rb 

### ISSUE THREAD

**Issue by medwards1771** [learn-co-curriculum/playlister-sinatra#16]
in lines 53-56 of 04_basic_view_spec.rb , the test says:

53   it "contains links to each song's show page" do
54        expect(page).to have_css("a[href='/artists/#{@artist.slug}']")
55      end
56    end

It should say:
53   it "contains links to each ARTIST'S show page" do

**Comment by jmburges** [comment]
Thanks @medwards1771 ! We fixed this with PR #26
