### ISSUE TITLE
another typo in 04_basic_view_spec.rb 

### ISSUE THREAD

**Issue by medwards1771** [learn-co-curriculum/playlister-sinatra#17]
lines 72-76 say:
72      it "contains links to each song's show page" do
73        expect(page).to have_css("a[href='/genres/#{@genre.slug}']")
74      end
75    end
76  end

should say:
72      it "contains links to each GENRE'S show page" do

**Comment by jmburges** [comment]
Thanks @medwards1771 we fixed this with #26
