### ISSUE TITLE
Checkboxes don't have names so the check methods in capybara don't work

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/playlister-sinatra#20]
This code (https://github.com/learn-co-curriculum/playlister-sinatra/blob/8369fded011ee99e85ef63fcc19baede5dcf125c/spec/features/05_song_form_spec.rb#L80-L81)  is looking for a checkbox with the is "hippity hoppity". Problem is, checkboxes are weird so students are having to make the name paramet hippitoy hoppity for this which is bad.

Instead, these tests should do something like checkbox.first to grab the first checkbox and then either check it or not check it. Which requires that the first checkbox is hippity hoppity. We are giving them the data so hopefully that doesn't matter. Worst comes to worst, we can do an id check

**Comment by vicfriedman** [comment]
@jmburges confused by this -- the capybara check method checks based on ID, name, or label (http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara/Node/Actions#check-instance_method)

you can do `first("input[type='checkbox']")` to get the first checkbox, but then you can extract any of the attributes of that checkbox. not sure how to proceed here.

**Comment by jmburges** [comment]
This is an issue that @JeffKatzy brought up. 

@JeffKatzy is there a student PR that shows the bad behavior you'd like to stop?

@vicfriedman feel free to move forward without closing this issue

**Comment by NoneOfMaster** [comment]
Maybe the issue here is that the first test in the spec 05_song_form_spec.rb looks for the wrong genre. It checks the box "New Age Garbage" and then tests for "Hippity Hop" which it won't and shouldn't find, right? So it fails. From the spec:

describe "Song Forms" do
  let(:artist_name) { "Person with a Face" }
  let(:genre_1_name) { "Hippity Hop" }   ######## SETS :genre_1_name to "Hippity Hop" ##########
  let(:genre_2_name) { "New Age Garbage" }
  let(:song_name) { "That One with the Guitar" }
  let!(:genre_1) { Genre.create(name: genre_1_name) }
  let!(:genre_2) { Genre.create(name: genre_2_name) }

  describe "/songs/new" do
    before do
      visit "/songs/new"
    end

    context "without an existing artist" do
      it "creates a new song and a new artist and associates them" do
        fill_in "Name", with: song_name
        check "New Age Garbage" ######## CHECKS "New Age Garbage" ##########
        fill_in "Artist Name", with: artist_name
        click_on "Create"

        expect(page).to have_content(song_name)
        expect(page).to have_content(artist_name)
        expect(page).to have_content(genre_1_name) ######## EXPECTS "Hippity Hop" ##########
        expect(page).to have_content("Successfully created song.")
      end
    end

**Comment by NoneOfMaster** [comment]
Also, I don't think that the first and second tests in this spec are distinct. So long as the first passes, it seems that the second does too.

**Comment by vicfriedman** [comment]
hey @NoneOfMaster 

Thanks for the feedback. The most recent version of this lab has fixed the issue with the genre (see this commit here: https://github.com/learn-co-curriculum/playlister-sinatra/commit/dd1202bd49ebd82d42159333488b6e552ea096d7)

Keep letting us know when you find issues!

**Comment by AnnJohn** [comment]
Closing this issue
