### ISSUE TITLE
Sinatra bug => update gemfile.lock

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/playlister-sinatra#28]
I was getting the following error: 

```
Failures:

  1) Song Forms /songs/new without an existing artist creates a new song and a new artist and associates them
     Failure/Error: visit "/songs/new"
     NoMethodError:
       undefined method `join' for #<String:0x007fea2525f0c8> 
```

from './spec/features/05_song_form_spec.rb:17'. After some research I found that this was a known bug in Sinatra 1.4.5. Even though I had the new gem, it wasn't being used here. Updating the Gemfile.lock to: 

```
sinatra (1.4.6)
```
 will fix that issue for future students.

**Comment by SophieDeBenedetto** [comment]
Hi @onyoo, can you be more specific about the context in which you saw this error? The above error is a very common one for Sinatra. I would consider it to be the default way that Sinatra will through errors when a number of problems occur, for example if there is a missing file (i.e. you are trying to render with `erb` a file that you haven't yet created`, Sinatra will show you this error. When you get this error, if you view the beginning of the stack trace of the error, you will see the *actual* error information, i.e, as in the above example, that you have a file missing.

**Comment by onyoo** [comment]
Hi @SophieDeBenedetto, unfortunately, I can't access the 'ask a question' conversation where I described the problem to Diane, and my terminal history has been cleared since. My search history is  providing no clear answers, but this is one of the documents I referenced that gave me the idea to use 1.4.6: https://github.com/sinatra/sinatra/issues/951.

I opened-up my finished playlister project and changed the Gemfile.lock to require Sinatra 1.4.5, bundled, and had no problems. However, I distinctly remember trying several fixes, and not being able to build without updating to 1.4.6.

I'm very sorry for not including more of the error message as I normally do. I was probably so excited about finally making headway, that I wasn't thinking about proper documentation..

**Comment by NoneOfMaster** [comment]
Hi All, I was having the exact same problem! On line 78 of the spec 04_basic_view_spec.rb, it has:

    visit "/songs/#{@song.slug}"

That raises the following error:

NoMethodError: undefined methodjoin' for #<String:0x007f978ecae2e8> from /Users/russelltepper/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in rescue in call'

I also found the same resource onyoo did: https://github.com/sinatra/sinatra/issues/951

Then I updated the Gemfile.lock, line 69 from: 
    sinatra (1.4.5)
to:
    sinatra (1.4.6)

And it solved the issue!

**Comment by vicfriedman** [comment]
hey @onyoo - I took a look at your solution (to compare to the master solution). 

I found this in your conotroller:

```
get '/songs/:slug/edit' do
    @song = Song.find_by_slug(params[:slug])
    erb :"songs/edit_song"
  end

  post '/songs/:slug/edit' do
    @song = Song.create(:name => params["Name"])
    @song.artist = Artist.find_or_create_by(:name => params["Artist Name"])
    params["genre"].each{|g| @song.genres << Genre.find_or_create_by(name: g)}
    @song.save
    erb :"songs/song_slug", :locals => {:message => "Song successfully updated."}
  end
```

The very first line of your edit action (`  post '/songs/:slug/edit'`) is actually creating a new song, instead of updating the current record. Instead of creating a new song, you would want to find the song in the database based on the slug in the URL `@song = Song.find_by_slug(params[:slug])`

From there, you can update the song based on the params `@song.update(params[:song])`

and then update the artist just like you had it ` @song.artist = Artist.find_or_create_by(name: params[:artist][:name])`

The final solution would look something like this:
```
patch '/songs/:slug' do
    @song = Song.find_by_slug(params[:slug])

    @song.update(params[:song])

    @song.artist = Artist.find_or_create_by(name: params[:artist][:name])
    @song.save

    erb :'songs/show', locals: {message: "Song successfully updated."}
  end
```

I'm closing this issue for now, please feel free to reach out with any other questions/issues!

**Comment by onyoo** [comment]
@vicfriedman, Thank you so much for pointing that out! That is a very good point! I'm not sure why I did that. I will review this lab. Sorry for the confusion. I will be more careful check the answer for bugs on my part next time!
