### ISSUE TITLE
05_song_form_spec.rb variable: 'genre_1_name' -> 'genre_2_name'

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/playlister-sinatra#29]
05_song_form_spec.rb:43 reads:

```expect(page).to have_content(genre_1_name)```

However, 'genre_1_name' was used correctly on line 25. Line 43 should read:

```expect(page).to have_content(genre_2_name)```

for the test to pass correctly.

**Comment by SophieDeBenedetto** [comment]
Hi @onyoo, thanks for raising this! a fix was pushed up earlier today so I'm closing this issue now.
