### ISSUE TITLE
instructions not detailed enough

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/playlister-sinatra#32]
It's my guess that this lab is meant to be challenging and more free-form. Even so, many students in the current class who are going through Sinatra content at home over the break have been stuck on this one. Looking over the instructions and the specs, I think we could give more instruction. 

Needs:
* A bit more to go on for the `#slug` and `.find_by_slug` methods. For example, "the `#slug` method should take a given song/artist/genre name and create the "slugified" version". The `.find_by_slug` method should use the `#slug` method"...Right now we don't even explicitly tell them to make these methods, you're just meant to figure it out from the specs. 
* Forms with multiple checkboxes, one for each genre, is really tough. Can we give an example or some more instruction. Also talk about this "checked" option? I'm not 100% positive but I don't *think* we really do a lot with checkboxes before this lab. 
* Concept of creating a flash message after updating a song isn't discussed anywhere, to my knowledge. There are a number of ways to achieve showing a "successfully updated" message after a song is updated but none of them are discussed or alluded to in this Readme. 
* The associations are confusing because the instructions give them hardly anything to go on. Can we flesh out "you are going to need a join table in there" to something a little more specific? For example, pose it as a question, like: "How would we implement the relationship of a song having many genres and genre having many songs? In order to establish a "many-to-many" relationship, we'll need a join table." I would recommend even explicitly stating you need a `SongGenres` class and table as the naming of this table tripped up a lot of students. 
* We need to tell them how to set up file structure. You can pass tests w/o having different controllers, subdirectories in views.

**Comment by AnnJohn** [comment]
@vicfriedman, i think you and @SophieDeBenedetto might have resolved this one already so if that's the case, then feel free to close
