### ISSUE TITLE
seed file usage unclear

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/playlister-sinatra#34]
this is first time students being required to interact with seed file. So we need to answer questions:

* what is the purpose of a seed file?
* what code belongs in there?

**Comment by AnnJohn** [comment]
@SophieDeBenedetto, i assigned this to vic, but did you write a lesson or update one to include info on seed files? thanks

**Comment by SophieDeBenedetto** [comment]
hey @AnnJohn, i ended up adding a section to this readme/code-along that talks about seed files.

**Comment by vicfriedman** [comment]
closing this issue - i've seen @SophieDeBenedetto's updates!
