### ISSUE TITLE
song_form_spec tests for the wrong genre name

### ISSUE THREAD

**Issue by flats** [learn-co-curriculum/playlister-sinatra#35]
In line 37 of spec/05_song_form_spec.rb, the Capybara tests check the checkbox labelled "Hippity Hop", which is the value assigned to the rspec variable `song_2_name`. Then, in line 43, the test checks for the presence of the variable `song_1_name`, as in the previous test. This line should read:
```ruby
expect(page).to have_content(genre_2_name)
```

**Comment by SophieDeBenedetto** [comment]
thanks @flats, fixed!
