### ISSUE TITLE
'require_all' doesn't seem to work

### ISSUE THREAD

**Issue by NoneOfMaster** [learn-co-curriculum/playlister-sinatra#37]
Though I'm not sure why, I believe that the 'require_all' implementation in this lab is not functioning properly. Modules in the lib/ folder are not found in the models. 

Like the library_parser in there also does, modules raise uninitializes constant errors in the namespaces of the classes where they are included. However, manually requiring the files at the top of the model file does the trick, so it seems to be 'require_all' that is the culprit.

**Comment by vicfriedman** [comment]
hi @NoneOfMaster could you please provide a little more context for this issue? Are you talking about the `require_all` in the config/environment.rb file?

You should only need to access library_parser in the `db/seeds.rb` file. 

Thanks!

**Comment by NoneOfMaster** [comment]
Yes that's the require_all I'm referring to. It doesn't seem to be successfully informing my lib/ folder of my models (or visa versa). Line 31-33 of library_parser in that folder needs to access them though:

    song = Song.create(name: song_name)
    genre = Genre.find_or_create_by(name: genre_name)
    artist = Artist.find_or_create_by(name: artist_name)

Instead, it raises uninitialized constant errors for Song, Genre, and Artist.

For example, initializing the parser at the bottom of library_parser.rb by adding 'LibraryParser.parse' to the very last line, and then running it from the command line with 'ruby lib/library_parser.rb', raises:

    lib/library_parser.rb:31:in `build_objects': uninitialized constant LibraryParser::Song (NameError)

Likewise, running the connection back in the reverse, I created a module in lib/ which which is not able to be found by my models. The module name was also raised as an uninitialized constant, in the same way as the above.

Example: a module called Slugs in a file lib/slugs.rb added to a the Artist model with the line 'include Slugs' raises:

    uninitialized constant Artist::Slugs (NameError)

**Comment by vicfriedman** [comment]
@NoneOfMaster thanks so much for this insight - i'll take a look right now!

**Comment by vicfriedman** [comment]
hey @NoneOfMaster I haven't been able to recreate this issue. Can you tell me where you're calling `LibraryParser.parse` to seed your database?
