### ISSUE TITLE
Issues with README - Wrong one on learn

### ISSUE THREAD

**Issue by dannyd4315** [learn-co-curriculum/playlister-sinatra#41]
There are issues with the readme on learn. The readme shown is for this lab learn-co-curriculum/playlister-sinatra however this is missing a lot of info. The correct readme and lab is here https://github.com/learn-co-students/playlister-sinatra-v-000 

This has all the information correct in the README on how to do the lab.

**Comment by AnnJohn** [comment]
Hi @dannyd4315 this looks like an issue with our deployer so thank you for raising the issue. We went ahead and redeployed the lab so it should be working again.
