### ISSUE TITLE
Sluggifiable Module is Using Wrong Pattern

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/playlister-sinatra#5]
The solution and test sluggifiable is based upon in memory storage from old playlisters.

An AR based sluggifiable module would basically implement https://github.com/technoweenie/permalink_fu or FriendlyId

That is to say, the module they create should automatically add a to_slug method to the model that writes to a column called slug and we could use this to introduce before_save.

**Comment by deniznida** [comment]
The new solution is not using modules for now.

**Comment by jmburges** [comment]
I think doing this without modules is completely fine. Maybe just put it in a comment in the solution that hey! we are repeating a ton of code. This should go into a module

**Comment by deniznida** [comment]
added comments to the models
