### ISSUE TITLE
Genre removal

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/playlister-sinatra#57]
Would suggest adding a test that checks that the application properly handles the removal of a song's genre during song editing.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#61.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
