### ISSUE TITLE
I have errors 

### ISSUE THREAD

**Issue by hana0070** [learn-co-curriculum/playlister-sinatra#58]
Hi 

I have errors and 2 instructors looked at it 
and nobody knows why it says errors. ... i already spent 3 days and dont know what to do

**Comment by curiositypaths** [comment]
Hi there,

Apologies for the issues you experienced while working on this lesson. Github issues are primarily used to raise issues about the content itself. The [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature might be the best way of raising support issues.

As always thank you for contributing.

**Comment by hana0070** [comment]
I did not even log in today. Do you think somebody hack my log in?

**Comment by curiositypaths** [comment]
No, we were just closing an old issue. It's from February 21st, 2017.

**Comment by hana0070** [comment]
OKAY THANKS
