### ISSUE TITLE
Rolling back migrations doesnt clear schema for test database

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/playlister-sinatra#68]
If you make an error building out your database tables and rollback your migrations and/or delete the schema, the test environment persists the database and prevents new migrations or changes from being migrated. There is no clear way to , the only way I could find around this after connecting with T.A.s and instructors and trying all form of rake commands (ie reset, clear, dump) to find a solution was to delete the entire lab, reclone, and start from scratch.

**Comment by maxwellbenton** [comment]
Hi @atxrenegade,

Thank you for providing feedback.

We have updated the materials in this lesson to include a section on how to drop and/or delete database tables if needed and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by atxrenegade** [comment]
So by fixing it you just stated the obvious and didnt address the issue at
all.

**Comment by atxrenegade** [comment]
Again. If you make an error building out your database tables **and rollback your migrations and/or delete the schema**, **the **test environment** persists the database **anyways** and prevents any new migrations or changes from being migrated.** There is no clear way to rollback migrations or delete  the database properly using the usual methods from a local environment. **The only way I could find around this issues after connecting with multiple T.A.s and instructors who also looked at, who also tried all form of rake commands (ie reset, clear, dump) and deleting the schema again** to find a solution. The only thing that worked was to delete the entire lab, recloned, and start from scratch.  Was this issue read at all when it was addressed, because your suggested solution was the first thing all three people tried with no success, and previously mentioned.
