### ISSUE TITLE
song.genres tests check for change in params[genre_name] rather than change in update in song.genres.all

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/playlister-sinatra#69]
The tests are could use better explaination. Maybe a picture of the forms would help alot. Since the readmes want a checklist, but the specs want a checklist but the test input too. Source: 11+ tech coach sessions of confusion.

**Comment by Sdcrouse** [comment]
I think I'm having a similar issue as well. My code appears to do the job right, but the last two tests are failing when they try to "uncheck" one genre and "check" another. Something like

```
1) Song Forms /songs/:slug/edit changing a song's genres updates the song's genres
     Failure/Error: check "Hippity Hop"

     Capybara::ElementNotFound:
       Unable to find checkbox "Hippity Hop" that is not disabled
```

**Comment by Sdcrouse** [comment]
Update: I added a label with the genre's name instead of putting the genre's name between an opening and closing input tag. Now I get this:

```
Failures:

  1) Song Forms /songs/:slug/edit changing a song's genres updates the song's genres
     Failure/Error: uncheck "New Age Garbage"

     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching visible checkbox "New Age Garbage" that is not disabled
```

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! This feedback has been logged and we'll take a look at this more closely and reassess the code in upcoming releases of this curriculum. 

As always, thanks for contributing! 💙
