### ISSUE TITLE
rack-flash instructions could be fleshed out

### ISSUE THREAD

**Issue by renojames** [learn-co-curriculum/playlister-sinatra#70]
Either the gem has changed, or the instructions linked in this section of the lab are not correct, because by following those instructions, I was not able to get around the "Uninitialized Constant Rack::Flash" error that students have reported previously, and ended up having to hard-code the message into the show route to pass the tests.

**Comment by Sdcrouse** [comment]
That happened to me, too. What you need to do is add `require 'rack-flash'` to the top of your songs_controller.rb file. The README doesn't mention this, but https://github.com/treeder/rack-flash#sinatra does.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
