### ISSUE TITLE
There's a key instruction missing in the Flash Message section.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/playlister-sinatra#72]
Hi. There's a key piece of code that is missing in the README in the Flash Message section (although, to be fair, it is shown in the https://github.com/treeder/rack-flash#sinatra link).

Unless students add `require 'rack-flash'` to the top of the appropriate controller, their programs will break with a `NameError: uninitialized constant Rack::Flash` message.

I hope this helps.

--- Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
