### ISSUE TITLE
I want to use Windows without install ubuntu

### ISSUE THREAD

**Issue by aabuauf** [learn-co-curriculum/playlister-sinatra#74]
How can I make ruby gem using windows without installing Ubuntu. 
I made my first project on visual studio on windows without installing Ubuntu. 
I tried to install lessons and try to run tests but it didn't work.

I want to know how to create ruby gem using windows without installing Ubuntu and run tests.

**Comment by drakeltheryuujin** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum. This sounds like an environment issue with an unsupported platform, which we unfortunately do not have the capacity to support at this time. I would recommend googling around about the problem.

I'm sorry, and good luck! 💙
